[package]
name = "markcat"
version = "1.1.0"
edition = "2021"
authors = ["Ted Pinkerton"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.5"
ignore = "0.4"

[dev-dependencies]
assert_cmd = "2.0"
assert_fs = "1.1"
predicates = "3.1"
tempfile = "3.20"
